### ISSUE TITLE
No Docker image available ?

### ISSUE THREAD

**Issue by nicolinuxfr** [phyber/docker-mdns#1]
Hello

Thanks for this project, which seems to do exactly what I'm searching for.

I tried using it based on the docker-compose.yml in the README file but I got this error when pulling : 

```
Error response from daemon: pull access denied for phyber/docker-mdns, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

It seems the image is not published on Docker Hub. Is this correct or is there an issue with the instructions ?

Thanks !
Nicolas

**Comment by phyber** [comment]
Hi,

Apologies for the confusion here. The images aren't on Docker Hub as you suspect, they're actually in the GitHub Container Repository and the image should be `ghcr.io/phyber/docker-mdns:aarch64-latest`, which is visible online at https://github.com/phyber/docker-mdns/pkgs/container/docker-mdns.

I'll fix up the README shortly. I should probably also try to tag the images nicely at some point 😅

**Comment by nicolinuxfr** [comment]
No problem, thanks for your quick answer. 🙂 

I think there is an authorization issue still. I have this error : 

```
Error response from daemon: Head "https://ghcr.io/v2/phyber/docker-mdns/manifests/aarch64-latest": unauthorized
```

And the URL you gave me leads to a 404.

**Comment by phyber** [comment]
Oh, interesting. Thanks for the heads up. I've made the repository public now, so hopefully you should be able to pull it shortly, if not immediately.

**Comment by nicolinuxfr** [comment]
Indeed, it's now working properly. Thanks ! 🙂
